sylius_ui:
    events:
        sylius.shop.layout.javascripts:
            blocks:
                mango_sylius.sylius_zasilkovna_plugin.shop.layout.javascripts:
                    template: "@MangoSyliusZasilkovnaPlugin/Shop/_javascripts.html.twig"
                    priority: 5

sylius_resource:
    resources:
        mango_zasilkovna_plugin.zasilkovna_config:
            driver: doctrine/orm
            classes:
                model: MangoSylius\SyliusZasilkovnaPlugin\Entity\ZasilkovnaConfig
                repository: MangoSylius\SyliusZasilkovnaPlugin\Repository\ZasilkovnaConfigRepository
                form: MangoSylius\SyliusZasilkovnaPlugin\Form\Type\ZasilkovnaConfigType
