parameters:
    shippingMethodsCodes: ['zasilkovna']
    mango_sylius_sylius_zasilkovna_plugin_payment_methods: ['cz', 'pl', 'sk', 'hu', 'ro']

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\SyliusZasilkovnaPlugin\Form\Extension\ShipmentZasilkovnaExtension:
        arguments:
            - '@sylius.shipping_methods_resolver'
            - '@sylius.repository.shipping_method'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType

    MangoSylius\SyliusZasilkovnaPlugin\Form\Extension\AdminZasilkovnaShippingMethodExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType

    MangoSylius\SyliusZasilkovnaPlugin\Form\Type\ZasilkovnaConfigType:
        tags:
            - name: form.type
        arguments:
            $countryChoices: '%mango_sylius_sylius_zasilkovna_plugin_payment_methods%'
            $dataClass: MangoSylius\SyliusZasilkovnaPlugin\Entity\ZasilkovnaConfig
            $validationGroups: ['sylius']

    MangoSylius\SyliusZasilkovnaPlugin\Model\ZasilkovnaShipmentExporter:
        public: true
        arguments:
            $currencyConverter: '@sylius.currency_converter'
            $shippingMethodsCodes: '%shippingMethodsCodes%'
        tags:
            - name: mango_sylius.shipment_exporter_type
              type: 'zasilkovna'
              label: 'Zásilkovna'
